services:
  postgres:
    image: postgres:16-alpine
    container_name: sportsleague-postgres
    environment:
      POSTGRES_DB: sports_league
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Karpatu2005
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sports_league"]
      interval: 5s
      timeout: 5s
      retries: 20

